/*
        stage('Stage 1') {
            steps {
                echo 'Hello world!' 
            }
        }*/
        stage('Clean Workspace'){
            steps{
                cleanWs()
            }
        }
